/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as _layoutRouteImport } from './routes/__layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LovepageLovepageIdRouteImport } from './routes/lovepage.$lovepageId'
import { Route as _layoutHomeRouteImport } from './routes/__layout/home'
import { Route as _layoutTemplateIndexRouteImport } from './routes/__layout/template/index'
import { Route as PaymentResultPageIdRouteImport } from './routes/payment.result.$pageId'
import { Route as ApiPaymentCreateRouteImport } from './routes/api.payment.create'
import { Route as ApiFlowReturnRouteImport } from './routes/api.flow.return'
import { Route as ApiFlowConfirmRouteImport } from './routes/api.flow.confirm'
import { Route as _layoutTemplateIdRouteImport } from './routes/__layout/template/$id'

const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const _layoutRoute = _layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovepageLovepageIdRoute = LovepageLovepageIdRouteImport.update({
  id: '/lovepage/$lovepageId',
  path: '/lovepage/$lovepageId',
  getParentRoute: () => rootRouteImport,
} as any)
const _layoutHomeRoute = _layoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutTemplateIndexRoute = _layoutTemplateIndexRouteImport.update({
  id: '/template/',
  path: '/template/',
  getParentRoute: () => _layoutRoute,
} as any)
const PaymentResultPageIdRoute = PaymentResultPageIdRouteImport.update({
  id: '/payment/result/$pageId',
  path: '/payment/result/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCreateRoute = ApiPaymentCreateRouteImport.update({
  id: '/api/payment/create',
  path: '/api/payment/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlowReturnRoute = ApiFlowReturnRouteImport.update({
  id: '/api/flow/return',
  path: '/api/flow/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlowConfirmRoute = ApiFlowConfirmRouteImport.update({
  id: '/api/flow/confirm',
  path: '/api/flow/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const _layoutTemplateIdRoute = _layoutTemplateIdRouteImport.update({
  id: '/template/$id',
  path: '/template/$id',
  getParentRoute: () => _layoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/home': typeof _layoutHomeRoute
  '/lovepage/$lovepageId': typeof LovepageLovepageIdRoute
  '/template/$id': typeof _layoutTemplateIdRoute
  '/api/flow/confirm': typeof ApiFlowConfirmRoute
  '/api/flow/return': typeof ApiFlowReturnRoute
  '/api/payment/create': typeof ApiPaymentCreateRoute
  '/payment/result/$pageId': typeof PaymentResultPageIdRoute
  '/template': typeof _layoutTemplateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/home': typeof _layoutHomeRoute
  '/lovepage/$lovepageId': typeof LovepageLovepageIdRoute
  '/template/$id': typeof _layoutTemplateIdRoute
  '/api/flow/confirm': typeof ApiFlowConfirmRoute
  '/api/flow/return': typeof ApiFlowReturnRoute
  '/api/payment/create': typeof ApiPaymentCreateRoute
  '/payment/result/$pageId': typeof PaymentResultPageIdRoute
  '/template': typeof _layoutTemplateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__layout': typeof _layoutRouteWithChildren
  '/preview': typeof PreviewRoute
  '/__layout/home': typeof _layoutHomeRoute
  '/lovepage/$lovepageId': typeof LovepageLovepageIdRoute
  '/__layout/template/$id': typeof _layoutTemplateIdRoute
  '/api/flow/confirm': typeof ApiFlowConfirmRoute
  '/api/flow/return': typeof ApiFlowReturnRoute
  '/api/payment/create': typeof ApiPaymentCreateRoute
  '/payment/result/$pageId': typeof PaymentResultPageIdRoute
  '/__layout/template/': typeof _layoutTemplateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preview'
    | '/home'
    | '/lovepage/$lovepageId'
    | '/template/$id'
    | '/api/flow/confirm'
    | '/api/flow/return'
    | '/api/payment/create'
    | '/payment/result/$pageId'
    | '/template'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preview'
    | '/home'
    | '/lovepage/$lovepageId'
    | '/template/$id'
    | '/api/flow/confirm'
    | '/api/flow/return'
    | '/api/payment/create'
    | '/payment/result/$pageId'
    | '/template'
  id:
    | '__root__'
    | '/'
    | '/__layout'
    | '/preview'
    | '/__layout/home'
    | '/lovepage/$lovepageId'
    | '/__layout/template/$id'
    | '/api/flow/confirm'
    | '/api/flow/return'
    | '/api/payment/create'
    | '/payment/result/$pageId'
    | '/__layout/template/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _layoutRoute: typeof _layoutRouteWithChildren
  PreviewRoute: typeof PreviewRoute
  LovepageLovepageIdRoute: typeof LovepageLovepageIdRoute
  ApiFlowConfirmRoute: typeof ApiFlowConfirmRoute
  ApiFlowReturnRoute: typeof ApiFlowReturnRoute
  ApiPaymentCreateRoute: typeof ApiPaymentCreateRoute
  PaymentResultPageIdRoute: typeof PaymentResultPageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__layout': {
      id: '/__layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovepage/$lovepageId': {
      id: '/lovepage/$lovepageId'
      path: '/lovepage/$lovepageId'
      fullPath: '/lovepage/$lovepageId'
      preLoaderRoute: typeof LovepageLovepageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__layout/home': {
      id: '/__layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof _layoutHomeRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/template/': {
      id: '/__layout/template/'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof _layoutTemplateIndexRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/payment/result/$pageId': {
      id: '/payment/result/$pageId'
      path: '/payment/result/$pageId'
      fullPath: '/payment/result/$pageId'
      preLoaderRoute: typeof PaymentResultPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/create': {
      id: '/api/payment/create'
      path: '/api/payment/create'
      fullPath: '/api/payment/create'
      preLoaderRoute: typeof ApiPaymentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flow/return': {
      id: '/api/flow/return'
      path: '/api/flow/return'
      fullPath: '/api/flow/return'
      preLoaderRoute: typeof ApiFlowReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flow/confirm': {
      id: '/api/flow/confirm'
      path: '/api/flow/confirm'
      fullPath: '/api/flow/confirm'
      preLoaderRoute: typeof ApiFlowConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__layout/template/$id': {
      id: '/__layout/template/$id'
      path: '/template/$id'
      fullPath: '/template/$id'
      preLoaderRoute: typeof _layoutTemplateIdRouteImport
      parentRoute: typeof _layoutRoute
    }
  }
}

interface _layoutRouteChildren {
  _layoutHomeRoute: typeof _layoutHomeRoute
  _layoutTemplateIdRoute: typeof _layoutTemplateIdRoute
  _layoutTemplateIndexRoute: typeof _layoutTemplateIndexRoute
}

const _layoutRouteChildren: _layoutRouteChildren = {
  _layoutHomeRoute: _layoutHomeRoute,
  _layoutTemplateIdRoute: _layoutTemplateIdRoute,
  _layoutTemplateIndexRoute: _layoutTemplateIndexRoute,
}

const _layoutRouteWithChildren =
  _layoutRoute._addFileChildren(_layoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _layoutRoute: _layoutRouteWithChildren,
  PreviewRoute: PreviewRoute,
  LovepageLovepageIdRoute: LovepageLovepageIdRoute,
  ApiFlowConfirmRoute: ApiFlowConfirmRoute,
  ApiFlowReturnRoute: ApiFlowReturnRoute,
  ApiPaymentCreateRoute: ApiPaymentCreateRoute,
  PaymentResultPageIdRoute: PaymentResultPageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
