/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as _layoutRouteImport } from './routes/__layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LovepageLovepageIdRouteImport } from './routes/lovepage.$lovepageId'
import { Route as _layoutHomeRouteImport } from './routes/__layout/home'
import { Route as _layoutTemplateIndexRouteImport } from './routes/__layout/template/index'
import { Route as _layoutTemplateIdRouteImport } from './routes/__layout/template/$id'
import { Route as _layoutLegalTerminosRouteImport } from './routes/__layout/legal/terminos'
import { Route as _layoutLegalReclamacionesRouteImport } from './routes/__layout/legal/reclamaciones'
import { Route as _layoutLegalDevolucionesRouteImport } from './routes/__layout/legal/devoluciones'

const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const _layoutRoute = _layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovepageLovepageIdRoute = LovepageLovepageIdRouteImport.update({
  id: '/lovepage/$lovepageId',
  path: '/lovepage/$lovepageId',
  getParentRoute: () => rootRouteImport,
} as any)
const _layoutHomeRoute = _layoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutTemplateIndexRoute = _layoutTemplateIndexRouteImport.update({
  id: '/template/',
  path: '/template/',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutTemplateIdRoute = _layoutTemplateIdRouteImport.update({
  id: '/template/$id',
  path: '/template/$id',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutLegalTerminosRoute = _layoutLegalTerminosRouteImport.update({
  id: '/legal/terminos',
  path: '/legal/terminos',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutLegalReclamacionesRoute =
  _layoutLegalReclamacionesRouteImport.update({
    id: '/legal/reclamaciones',
    path: '/legal/reclamaciones',
    getParentRoute: () => _layoutRoute,
  } as any)
const _layoutLegalDevolucionesRoute =
  _layoutLegalDevolucionesRouteImport.update({
    id: '/legal/devoluciones',
    path: '/legal/devoluciones',
    getParentRoute: () => _layoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/home': typeof _layoutHomeRoute
  '/lovepage/$lovepageId': typeof LovepageLovepageIdRoute
  '/legal/devoluciones': typeof _layoutLegalDevolucionesRoute
  '/legal/reclamaciones': typeof _layoutLegalReclamacionesRoute
  '/legal/terminos': typeof _layoutLegalTerminosRoute
  '/template/$id': typeof _layoutTemplateIdRoute
  '/template': typeof _layoutTemplateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/home': typeof _layoutHomeRoute
  '/lovepage/$lovepageId': typeof LovepageLovepageIdRoute
  '/legal/devoluciones': typeof _layoutLegalDevolucionesRoute
  '/legal/reclamaciones': typeof _layoutLegalReclamacionesRoute
  '/legal/terminos': typeof _layoutLegalTerminosRoute
  '/template/$id': typeof _layoutTemplateIdRoute
  '/template': typeof _layoutTemplateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__layout': typeof _layoutRouteWithChildren
  '/preview': typeof PreviewRoute
  '/__layout/home': typeof _layoutHomeRoute
  '/lovepage/$lovepageId': typeof LovepageLovepageIdRoute
  '/__layout/legal/devoluciones': typeof _layoutLegalDevolucionesRoute
  '/__layout/legal/reclamaciones': typeof _layoutLegalReclamacionesRoute
  '/__layout/legal/terminos': typeof _layoutLegalTerminosRoute
  '/__layout/template/$id': typeof _layoutTemplateIdRoute
  '/__layout/template/': typeof _layoutTemplateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preview'
    | '/home'
    | '/lovepage/$lovepageId'
    | '/legal/devoluciones'
    | '/legal/reclamaciones'
    | '/legal/terminos'
    | '/template/$id'
    | '/template'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preview'
    | '/home'
    | '/lovepage/$lovepageId'
    | '/legal/devoluciones'
    | '/legal/reclamaciones'
    | '/legal/terminos'
    | '/template/$id'
    | '/template'
  id:
    | '__root__'
    | '/'
    | '/__layout'
    | '/preview'
    | '/__layout/home'
    | '/lovepage/$lovepageId'
    | '/__layout/legal/devoluciones'
    | '/__layout/legal/reclamaciones'
    | '/__layout/legal/terminos'
    | '/__layout/template/$id'
    | '/__layout/template/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _layoutRoute: typeof _layoutRouteWithChildren
  PreviewRoute: typeof PreviewRoute
  LovepageLovepageIdRoute: typeof LovepageLovepageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__layout': {
      id: '/__layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovepage/$lovepageId': {
      id: '/lovepage/$lovepageId'
      path: '/lovepage/$lovepageId'
      fullPath: '/lovepage/$lovepageId'
      preLoaderRoute: typeof LovepageLovepageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__layout/home': {
      id: '/__layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof _layoutHomeRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/template/': {
      id: '/__layout/template/'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof _layoutTemplateIndexRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/template/$id': {
      id: '/__layout/template/$id'
      path: '/template/$id'
      fullPath: '/template/$id'
      preLoaderRoute: typeof _layoutTemplateIdRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/legal/terminos': {
      id: '/__layout/legal/terminos'
      path: '/legal/terminos'
      fullPath: '/legal/terminos'
      preLoaderRoute: typeof _layoutLegalTerminosRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/legal/reclamaciones': {
      id: '/__layout/legal/reclamaciones'
      path: '/legal/reclamaciones'
      fullPath: '/legal/reclamaciones'
      preLoaderRoute: typeof _layoutLegalReclamacionesRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/legal/devoluciones': {
      id: '/__layout/legal/devoluciones'
      path: '/legal/devoluciones'
      fullPath: '/legal/devoluciones'
      preLoaderRoute: typeof _layoutLegalDevolucionesRouteImport
      parentRoute: typeof _layoutRoute
    }
  }
}

interface _layoutRouteChildren {
  _layoutHomeRoute: typeof _layoutHomeRoute
  _layoutLegalDevolucionesRoute: typeof _layoutLegalDevolucionesRoute
  _layoutLegalReclamacionesRoute: typeof _layoutLegalReclamacionesRoute
  _layoutLegalTerminosRoute: typeof _layoutLegalTerminosRoute
  _layoutTemplateIdRoute: typeof _layoutTemplateIdRoute
  _layoutTemplateIndexRoute: typeof _layoutTemplateIndexRoute
}

const _layoutRouteChildren: _layoutRouteChildren = {
  _layoutHomeRoute: _layoutHomeRoute,
  _layoutLegalDevolucionesRoute: _layoutLegalDevolucionesRoute,
  _layoutLegalReclamacionesRoute: _layoutLegalReclamacionesRoute,
  _layoutLegalTerminosRoute: _layoutLegalTerminosRoute,
  _layoutTemplateIdRoute: _layoutTemplateIdRoute,
  _layoutTemplateIndexRoute: _layoutTemplateIndexRoute,
}

const _layoutRouteWithChildren =
  _layoutRoute._addFileChildren(_layoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _layoutRoute: _layoutRouteWithChildren,
  PreviewRoute: PreviewRoute,
  LovepageLovepageIdRoute: LovepageLovepageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
