/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _layoutRouteImport } from './routes/__layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LovepageLovepageIdRouteImport } from './routes/lovepage.$lovepageId'
import { Route as ApiActivateRouteImport } from './routes/api.activate'
import { Route as _layoutHomeRouteImport } from './routes/__layout/home'
import { Route as _layoutTemplateIndexRouteImport } from './routes/__layout/template/index'
import { Route as _layoutTemplateIdRouteImport } from './routes/__layout/template/$id'

const _layoutRoute = _layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovepageLovepageIdRoute = LovepageLovepageIdRouteImport.update({
  id: '/lovepage/$lovepageId',
  path: '/lovepage/$lovepageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivateRoute = ApiActivateRouteImport.update({
  id: '/api/activate',
  path: '/api/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const _layoutHomeRoute = _layoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutTemplateIndexRoute = _layoutTemplateIndexRouteImport.update({
  id: '/template/',
  path: '/template/',
  getParentRoute: () => _layoutRoute,
} as any)
const _layoutTemplateIdRoute = _layoutTemplateIdRouteImport.update({
  id: '/template/$id',
  path: '/template/$id',
  getParentRoute: () => _layoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof _layoutHomeRoute
  '/api/activate': typeof ApiActivateRoute
  '/lovepage/$lovepageId': typeof LovepageLovepageIdRoute
  '/template/$id': typeof _layoutTemplateIdRoute
  '/template': typeof _layoutTemplateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof _layoutHomeRoute
  '/api/activate': typeof ApiActivateRoute
  '/lovepage/$lovepageId': typeof LovepageLovepageIdRoute
  '/template/$id': typeof _layoutTemplateIdRoute
  '/template': typeof _layoutTemplateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__layout': typeof _layoutRouteWithChildren
  '/__layout/home': typeof _layoutHomeRoute
  '/api/activate': typeof ApiActivateRoute
  '/lovepage/$lovepageId': typeof LovepageLovepageIdRoute
  '/__layout/template/$id': typeof _layoutTemplateIdRoute
  '/__layout/template/': typeof _layoutTemplateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/api/activate'
    | '/lovepage/$lovepageId'
    | '/template/$id'
    | '/template'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/api/activate'
    | '/lovepage/$lovepageId'
    | '/template/$id'
    | '/template'
  id:
    | '__root__'
    | '/'
    | '/__layout'
    | '/__layout/home'
    | '/api/activate'
    | '/lovepage/$lovepageId'
    | '/__layout/template/$id'
    | '/__layout/template/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _layoutRoute: typeof _layoutRouteWithChildren
  ApiActivateRoute: typeof ApiActivateRoute
  LovepageLovepageIdRoute: typeof LovepageLovepageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__layout': {
      id: '/__layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovepage/$lovepageId': {
      id: '/lovepage/$lovepageId'
      path: '/lovepage/$lovepageId'
      fullPath: '/lovepage/$lovepageId'
      preLoaderRoute: typeof LovepageLovepageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activate': {
      id: '/api/activate'
      path: '/api/activate'
      fullPath: '/api/activate'
      preLoaderRoute: typeof ApiActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__layout/home': {
      id: '/__layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof _layoutHomeRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/template/': {
      id: '/__layout/template/'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof _layoutTemplateIndexRouteImport
      parentRoute: typeof _layoutRoute
    }
    '/__layout/template/$id': {
      id: '/__layout/template/$id'
      path: '/template/$id'
      fullPath: '/template/$id'
      preLoaderRoute: typeof _layoutTemplateIdRouteImport
      parentRoute: typeof _layoutRoute
    }
  }
}

interface _layoutRouteChildren {
  _layoutHomeRoute: typeof _layoutHomeRoute
  _layoutTemplateIdRoute: typeof _layoutTemplateIdRoute
  _layoutTemplateIndexRoute: typeof _layoutTemplateIndexRoute
}

const _layoutRouteChildren: _layoutRouteChildren = {
  _layoutHomeRoute: _layoutHomeRoute,
  _layoutTemplateIdRoute: _layoutTemplateIdRoute,
  _layoutTemplateIndexRoute: _layoutTemplateIndexRoute,
}

const _layoutRouteWithChildren =
  _layoutRoute._addFileChildren(_layoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _layoutRoute: _layoutRouteWithChildren,
  ApiActivateRoute: ApiActivateRoute,
  LovepageLovepageIdRoute: LovepageLovepageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
